In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [9]:
x = torch.from_numpy(arr)

In [10]:
type(x)

torch.Tensor

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [12]:
x

tensor([1, 2, 3, 4, 5])

In [13]:
x.dtype

torch.int64

In [14]:
arr2d = np.arange(0.0,12.0)

In [16]:
arr2d = arr2d.reshape(4,3)

In [18]:
x2 = torch.from_numpy(arr2d)

In [19]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
x

tensor([1, 2, 3, 4, 5])

In [22]:
arr[0] = 99

In [23]:
arr

array([99,  2,  3,  4,  5])

In [24]:
# Direct link to arr
x

tensor([99,  2,  3,  4,  5])

In [25]:
my_arr = np.arange(0,10)

In [26]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# No direct link to my_arr
my_tensor = torch.tensor(my_arr)

In [28]:
# Direct link to my_arr
my_other_tensor = torch.from_numpy(my_arr)

In [29]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_arr[0] = 99

In [32]:
my_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [33]:
my_other_tensor

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [34]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
new_arr = np.array([1,2,3])

In [36]:
new_arr.dtype

dtype('int64')

In [37]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [38]:
# Float tensor
my_tensor = torch.Tensor(new_arr)

In [39]:
my_tensor.dtype

torch.float32

In [40]:
# Computers have limit on store float accuracy
torch.empty(2,2)

tensor([[0.0000e+00, 1.8750e+00],
        [2.3694e-38, 0.0000e+00]])

In [41]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [42]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [43]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [46]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [47]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [48]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [49]:
my_tensor = torch.tensor([1,2,3])

In [50]:
my_tensor.dtype

torch.int64

In [51]:
my_tensor = my_tensor.type(torch.int32)

In [52]:
my_tensor.dtype

torch.int32

In [53]:
# Uniform distribution
torch.rand(4,3)

tensor([[0.1351, 0.3077, 0.6826],
        [0.4742, 0.7693, 0.9421],
        [0.8118, 0.5193, 0.8081],
        [0.9358, 0.4937, 0.0120]])

In [54]:
# Standard normal distribution
torch.randn(4,3)

tensor([[-0.4876, -0.7773,  0.7294],
        [ 0.9517,  0.5793, -1.5762],
        [ 1.5276, -0.9156,  0.4998],
        [ 0.0341,  0.2438, -1.8208]])

In [55]:
torch.randint(low=0,high=10,size=(5,5))

tensor([[0, 3, 7, 7, 9],
        [6, 6, 4, 5, 7],
        [4, 1, 3, 3, 4],
        [3, 1, 9, 3, 8],
        [0, 6, 9, 0, 0]])

In [56]:
x = torch.zeros(2,5)

In [57]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [58]:
x.shape

torch.Size([2, 5])

In [59]:
# Like the shape of x
torch.rand_like(x)

tensor([[0.9801, 0.9130, 0.0380, 0.7126, 0.4021],
        [0.5261, 0.7686, 0.6428, 0.7446, 0.1159]])

In [60]:
torch.randn_like(x)

tensor([[ 1.4408, -1.1946, -0.4660, -0.9032, -0.7208],
        [-0.1799,  0.2572,  1.2915, -1.4064, -0.4790]])

In [61]:
torch.randint_like(x,low=0,high=11)

tensor([[ 3.,  9.,  1.,  7.,  1.],
        [ 9.,  1.,  2.,  3., 10.]])

In [62]:
torch.manual_seed(42)         #Arbitrary number
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [63]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [64]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [65]:
x = torch.arange(6).reshape(3,2)

In [66]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [67]:
type(x[1,1])

torch.Tensor

In [68]:
x[:,1]

tensor([1, 3, 5])

In [69]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [70]:
x = torch.arange(10)

In [71]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [73]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x = torch.arange(10)

In [77]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
x.shape

torch.Size([10])

In [79]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [80]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
z = x.view(2,5)

In [82]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [83]:
x[0] = 9999

In [84]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [85]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [86]:
x = torch.arange(10)

In [87]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
x.shape

torch.Size([10])

In [89]:
# Infer what the 2nd dimension
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [90]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [102]:
a = torch.tensor([1.,2.,3.])

In [103]:
b = torch.tensor([4.,5.,6.])

In [93]:
a

tensor([1., 2., 3.])

In [94]:
a.dtype

torch.float32

In [95]:
b

tensor([4., 5., 6.])

In [96]:
a + b

tensor([5., 7., 9.])

In [97]:
torch.add(a,b)

tensor([5., 7., 9.])

In [98]:
a.mul(b)

tensor([ 4., 10., 18.])

In [99]:
a

tensor([1., 2., 3.])

In [100]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [101]:
a

tensor([ 4., 10., 18.])

In [104]:
a.dot(b)

tensor(32.)

In [106]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [107]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [108]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [109]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [110]:
a.shape

torch.Size([2, 3])

In [111]:
b.shape

torch.Size([3, 2])

In [112]:
# Matrix multiplication
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [113]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [114]:
x = torch.tensor([2.,3.,4.,5.])

In [115]:
# Euclidian norm
x.norm()

tensor(7.3485)

In [116]:
# Number of elements
x.numel()

4

In [117]:
len(x)

4

In [118]:
# Number of rows
len(a)

2

In [119]:
# Number of elements
a.numel()

6