In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a','b','c']

In [4]:
mylist = [10,20,30]

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([10, 20, 30])

In [7]:
d = {'a':10,'b':20,'c':30}

In [9]:
pd.Series(data=mylist)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(data=arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(data=[10,'a',4.4])

0     10
1      a
2    4.4
dtype: object

In [12]:
ser1 = pd.Series([1,2,3,4],index=['USA','Germany','USSR','Japan'])

In [13]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [14]:
ser1['USA']

1

In [15]:
ser2 = pd.Series([1,4,5,6],index=['USA','Germany','Italy','Japan'])

In [16]:
ser2

USA        1
Germany    4
Italy      5
Japan      6
dtype: int64

In [17]:
ser1 + ser2

Germany     6.0
Italy       NaN
Japan      10.0
USA         2.0
USSR        NaN
dtype: float64

In [18]:
from numpy.random import randn
np.random.seed(101)

rand_mat = randn(5,4)

In [19]:
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [20]:
df = pd.DataFrame(data=rand_mat)

In [21]:
df

0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [25]:
df = pd.DataFrame(data=rand_mat,index='A B C D E'.split(), columns='W X Y Z'.split())

In [26]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [27]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [28]:
type(df['W'])

pandas.core.series.Series

In [29]:
mylist = ['W','Y']

In [30]:
df[mylist]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [31]:
df[['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [32]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [33]:
df['NEW'] = df['W'] + df['Y']

In [34]:
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [37]:
df.drop('NEW',axis=1,inplace=True)

In [38]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [39]:
df.drop('C')

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [41]:
#Index location
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [42]:
df.loc[['A','E']]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [43]:
df.iloc[[0,3]]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
D  0.188695 -0.758872 -0.933237  0.955057

In [45]:
df.loc[['A','B']][['Y','Z']]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965

In [46]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [47]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [48]:
df_bool = df>0

In [49]:
df[df_bool]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [50]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [51]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [52]:
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [53]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [54]:
df[df['W']>0]['Y'].loc['A']

0.9079694464765431

In [55]:
cond1 = df['W'] > 0
cond2 = df['Y'] > 1

In [56]:
df[ cond1 and cond2]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [57]:
df[(cond1) & (cond2)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [58]:
df[(df['W'] > 0) & (df['Y'] > 1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [59]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [60]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [61]:
new_ind = 'CA NY WY OR CO'.split()

In [62]:
new_ind

['CA', 'NY', 'WY', 'OR', 'CO']

In [63]:
df['States'] = new_ind

In [64]:
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [66]:
df.set_index('States',inplace=True)

In [67]:
df

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
W    5 non-null float64
X    5 non-null float64
Y    5 non-null float64
Z    5 non-null float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [69]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [70]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [71]:
df['W'] > 0

States
CA     True
NY     True
WY    False
OR     True
CO     True
Name: W, dtype: bool

In [72]:
ser_w = df['W'] > 0

In [73]:
ser_w.value_counts()

True     4
False    1
Name: W, dtype: int64

In [74]:
sum(ser_w)

4

In [75]:
len(ser_w)

5

In [76]:
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [77]:
df = pd.DataFrame(data)

In [78]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [79]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [80]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [86]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [82]:
df['col2'].unique()

array([444, 555, 666])

In [83]:
df['col2'].nunique()

3

In [84]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [87]:
# Col 1 > 2
# col2 == 444

newdf = df[(df['col1'] > 2) & (df['col2'] == 444)]

In [88]:
newdf

col1  col2 col3
3     4   444  xyz

In [89]:
def times_two(number):
    return number*2

In [90]:
times_two(4)

8

In [92]:
df['new'] = df['col1'].apply(times_two)

In [93]:
df

col1  col2 col3  new
0     1   444  abc    2
1     2   555  def    4
2     3   666  ghi    6
3     4   444  xyz    8

In [94]:
del df['new']

In [95]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [96]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [97]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
col1    4 non-null int64
col2    4 non-null int64
col3    4 non-null object
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [99]:
df.describe()

col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [101]:
df.sort_values('col2',ascending=False)

col1  col2 col3
2     3   666  ghi
1     2   555  def
0     1   444  abc
3     4   444  xyz

In [108]:
pwd

'/Users/maximillian/Desktop/求职/Machine Learning/PyTorch/PYTORCH_NOTEBOOKS/00-Crash-Course-Topics'

In [111]:
df = pd.read_csv("/Users/maximillian/Desktop/求职/Machine Learning/PyTorch/PYTORCH_NOTEBOOKS/00-Crash-Course-Topics/01-Crash-Course-Pandas/example.csv")

In [112]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [113]:
newdf = df[['a','b']]

In [114]:
newdf.to_csv('mynew.csv',index=False)

In [116]:
df = pd.read_excel("/Users/maximillian/Desktop/求职/Machine Learning/PyTorch/PYTORCH_NOTEBOOKS/00-Crash-Course-Topics/01-Crash-Course-Pandas/Excel_Sample.xlsx",sheet_name='Sheet1')

In [119]:
df

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [120]:
df.columns

Index(['Unnamed: 0', 'a', 'b', 'c', 'd'], dtype='object')

In [121]:
df.drop('Unnamed: 0',axis=1)

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [123]:
mylist_of_tables = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [124]:
type(mylist_of_tables)

list

In [125]:
len(mylist_of_tables)

1

In [126]:
df = mylist_of_tables[0]

In [128]:
df.head()

Bank NameBank           CityCity StateSt  CertCert  \
0                 Almena State Bank             Almena      KS     15426   
1        First City Bank of Florida  Fort Walton Beach      FL     16748   
2              The First State Bank      Barboursville      WV     14361   
3                Ericson State Bank            Ericson      NE     18265   
4  City National Bank of New Jersey             Newark      NJ     21111   

      Acquiring InstitutionAI Closing DateClosing  FundFund  
0                 Equity Bank    October 23, 2020     10538  
1   United Fidelity Bank, fsb    October 16, 2020     10537  
2              MVB Bank, Inc.       April 3, 2020     10536  
3  Farmers and Merchants Bank   February 14, 2020     10535  
4             Industrial Bank    November 1, 2019     10534