In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
with open('../Data/shakespeare.txt','r',encoding='utf8') as f:
    text = f.read()

In [4]:
type(text)

str

In [5]:
# Raw string
text[:1000]     # \n stands for a new line

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bud buriest thy content,\n  And tender churl mak'st waste in niggarding:\n    Pity the world, or else this glutton be,\n    To eat the world's due, by the grave and thee.\n\n\n                     2\n  When forty winters shall besiege thy brow,\n  And dig deep trenches in thy beauty's field,\n  Thy youth's proud livery so gazed on now,\n  Will be a tattered weed of small worth held:  \n  Then being asked, where all thy beauty lies,\n  Where all the treasure of thy lusty days;\n  To sa

In [6]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [7]:
len(text)

5445609

In [8]:
all_characters = set(text)

In [9]:
all_characters

{'\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}'}

In [10]:
len(all_characters)

84

In [11]:
for pair in enumerate(all_characters):
    print(pair)

(0, 'r')
(1, 'C')
(2, 'Z')
(3, '3')
(4, 'l')
(5, 'U')
(6, 'M')
(7, 'q')
(8, 'E')
(9, 'T')
(10, ',')
(11, ';')
(12, '>')
(13, 't')
(14, 'k')
(15, '6')
(16, 'L')
(17, 'c')
(18, 'R')
(19, 'f')
(20, 'K')
(21, 'g')
(22, 'o')
(23, '5')
(24, 'n')
(25, "'")
(26, 'H')
(27, 'b')
(28, '}')
(29, 'j')
(30, 'X')
(31, '|')
(32, 'G')
(33, 'd')
(34, '?')
(35, 'W')
(36, 'm')
(37, 'p')
(38, 'V')
(39, 'B')
(40, 'J')
(41, '_')
(42, '`')
(43, 'y')
(44, 'P')
(45, '&')
(46, 'i')
(47, 'z')
(48, 's')
(49, '4')
(50, 'N')
(51, 'h')
(52, ')')
(53, 'O')
(54, 'v')
(55, ' ')
(56, 'I')
(57, 'Y')
(58, 'x')
(59, 'Q')
(60, '8')
(61, '[')
(62, 'a')
(63, '"')
(64, 'u')
(65, 'S')
(66, '9')
(67, '0')
(68, '2')
(69, 'e')
(70, '\n')
(71, '1')
(72, 'D')
(73, '7')
(74, 'F')
(75, 'w')
(76, '<')
(77, '-')
(78, ':')
(79, 'A')
(80, '(')
(81, ']')
(82, '.')
(83, '!')


In [12]:
# Transform number values to letters
decoder = dict(enumerate(all_characters))

In [13]:
decoder

{0: 'r',
 1: 'C',
 2: 'Z',
 3: '3',
 4: 'l',
 5: 'U',
 6: 'M',
 7: 'q',
 8: 'E',
 9: 'T',
 10: ',',
 11: ';',
 12: '>',
 13: 't',
 14: 'k',
 15: '6',
 16: 'L',
 17: 'c',
 18: 'R',
 19: 'f',
 20: 'K',
 21: 'g',
 22: 'o',
 23: '5',
 24: 'n',
 25: "'",
 26: 'H',
 27: 'b',
 28: '}',
 29: 'j',
 30: 'X',
 31: '|',
 32: 'G',
 33: 'd',
 34: '?',
 35: 'W',
 36: 'm',
 37: 'p',
 38: 'V',
 39: 'B',
 40: 'J',
 41: '_',
 42: '`',
 43: 'y',
 44: 'P',
 45: '&',
 46: 'i',
 47: 'z',
 48: 's',
 49: '4',
 50: 'N',
 51: 'h',
 52: ')',
 53: 'O',
 54: 'v',
 55: ' ',
 56: 'I',
 57: 'Y',
 58: 'x',
 59: 'Q',
 60: '8',
 61: '[',
 62: 'a',
 63: '"',
 64: 'u',
 65: 'S',
 66: '9',
 67: '0',
 68: '2',
 69: 'e',
 70: '\n',
 71: '1',
 72: 'D',
 73: '7',
 74: 'F',
 75: 'w',
 76: '<',
 77: '-',
 78: ':',
 79: 'A',
 80: '(',
 81: ']',
 82: '.',
 83: '!'}

In [14]:
# Transform letters to number values
encoder = {char: ind for ind,char in decoder.items()}      # ind = index

In [15]:
encoder

{'r': 0,
 'C': 1,
 'Z': 2,
 '3': 3,
 'l': 4,
 'U': 5,
 'M': 6,
 'q': 7,
 'E': 8,
 'T': 9,
 ',': 10,
 ';': 11,
 '>': 12,
 't': 13,
 'k': 14,
 '6': 15,
 'L': 16,
 'c': 17,
 'R': 18,
 'f': 19,
 'K': 20,
 'g': 21,
 'o': 22,
 '5': 23,
 'n': 24,
 "'": 25,
 'H': 26,
 'b': 27,
 '}': 28,
 'j': 29,
 'X': 30,
 '|': 31,
 'G': 32,
 'd': 33,
 '?': 34,
 'W': 35,
 'm': 36,
 'p': 37,
 'V': 38,
 'B': 39,
 'J': 40,
 '_': 41,
 '`': 42,
 'y': 43,
 'P': 44,
 '&': 45,
 'i': 46,
 'z': 47,
 's': 48,
 '4': 49,
 'N': 50,
 'h': 51,
 ')': 52,
 'O': 53,
 'v': 54,
 ' ': 55,
 'I': 56,
 'Y': 57,
 'x': 58,
 'Q': 59,
 '8': 60,
 '[': 61,
 'a': 62,
 '"': 63,
 'u': 64,
 'S': 65,
 '9': 66,
 '0': 67,
 '2': 68,
 'e': 69,
 '\n': 70,
 '1': 71,
 'D': 72,
 '7': 73,
 'F': 74,
 'w': 75,
 '<': 76,
 '-': 77,
 ':': 78,
 'A': 79,
 '(': 80,
 ']': 81,
 '.': 82,
 '!': 83}

In [16]:
encoded_text = np.array([encoder[char] for char in text])

In [17]:
encoded_text[:500]

array([70, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
       55, 55, 55, 55, 55, 71, 70, 55, 55, 74,  0, 22, 36, 55, 19, 62, 46,
        0, 69, 48, 13, 55, 17,  0, 69, 62, 13, 64,  0, 69, 48, 55, 75, 69,
       55, 33, 69, 48, 46,  0, 69, 55, 46, 24, 17,  0, 69, 62, 48, 69, 10,
       70, 55, 55,  9, 51, 62, 13, 55, 13, 51, 69,  0, 69, 27, 43, 55, 27,
       69, 62, 64, 13, 43, 25, 48, 55,  0, 22, 48, 69, 55, 36, 46, 21, 51,
       13, 55, 24, 69, 54, 69,  0, 55, 33, 46, 69, 10, 70, 55, 55, 39, 64,
       13, 55, 62, 48, 55, 13, 51, 69, 55,  0, 46, 37, 69,  0, 55, 48, 51,
       22, 64,  4, 33, 55, 27, 43, 55, 13, 46, 36, 69, 55, 33, 69, 17, 69,
       62, 48, 69, 10, 70, 55, 55, 26, 46, 48, 55, 13, 69, 24, 33, 69,  0,
       55, 51, 69, 46,  0, 55, 36, 46, 21, 51, 13, 55, 27, 69, 62,  0, 55,
       51, 46, 48, 55, 36, 69, 36, 22,  0, 43, 78, 70, 55, 55, 39, 64, 13,
       55, 13, 51, 22, 64, 55, 17, 22, 24, 13,  0, 62, 17, 13, 69, 33, 55,
       13, 22, 55, 13, 51

In [18]:
decoder[55]

' '

In [19]:
decoder[66]

'9'

In [20]:
def one_hot_encoder(encoded_text,num_uni_chars):
    
    # encoded_text = batch of encoded text
    # num_uni_chars = len(set(text))
    
    one_hot = np.zeros((encoded_text.size,num_uni_chars))   # Initialize with zeros
    
    one_hot = one_hot.astype(np.float32)
    
    # Explanation: https://stackoverflow.com/questions/29831489/convert-array-of-indices-to-1-hot-encoded-numpy-array
    one_hot[np.arange(one_hot.shape[0]),encoded_text.flatten()] = 1.0
    
    one_hot = one_hot.reshape((*encoded_text.shape,num_uni_chars))    # Reshape to match the batch shape
    
    return one_hot

In [21]:
# Test array
arr = np.array([1,2,0])

In [22]:
arr

array([1, 2, 0])

In [28]:
one_hot_encoder(arr,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [29]:
example_text = np.arange(10)

In [30]:
example_text

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
example_text.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
def generate_batches(encoded_text,samp_per_batch=10,seq_len=50):
    
    # X: Encoded text of length seq_len
    # [0, 1, 2]
    # [1, 2, 3]
    # ...
    
    # Y: Encoded text shifted by one with same length as X
    # [1, 2, 3]
    # [2, 3, 4]
    # ...
    
    # How many chars per batch?
    char_per_batch = samp_per_batch * seq_len
    
    # How many batches can we make, given the len of encoded text?
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    
    # Cut off the end of the encoded text, that won't fit evenly into a batch
    encoded_text = encoded_text[:num_batches_avail*char_per_batch]
    
    encoded_text = encoded_text.reshape((samp_per_batch,-1))
    
    for n in range(0,encoded_text.shape[1],seq_len):
        
        x = encoded_text[:,n:n+seq_len]
        
        # Create a zeros array to the same shape as x
        y = np.zeros_like(x)
        
        try:
            
            y[:,:-1] = x[:,1:]
            y[:,-1] = encoded_text[:,n+seq_len]
            
        except:
            
            y[:,:-1] = x[:,1:]
            y[:,-1] = encoded_text[:,0]
            
        yield x,y

In [33]:
sample_text = encoded_text[:20]

In [39]:
sample_text = np.arange(20)

In [40]:
sample_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
batch_generator = generate_batches(sample_text,samp_per_batch=2,seq_len=5)

In [42]:
x,y = next(batch_generator)

In [43]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [44]:
y

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [45]:
class CharModel(nn.Module):
    
    def __init__(self,all_chars,num_hidden=256,num_layers=4,drop_prob=0.5,use_gpu=False):
        
        super().__init__()
        
        self.drop_prob = drop_prob
        self.num_layers = num_layers
        self.num_hidden = num_hidden
        self.use_gpu = use_gpu
        
        self.all_chars = all_chars
        self.decoder = dict(enumerate(all_chars))
        self.encoder = {char:ind for ind,char in decoder.items()}
        
        self.lstm = nn.LSTM(len(self.all_chars),num_hidden,num_layers,dropout=drop_prob,batch_first=True)
        
        self.dropout = nn.Dropout(drop_prob)
        
        self.fc_linear = nn.Linear(num_hidden,len(self.all_chars))
        
    def forward(self,x,hidden):
        
        lstm_output , hidden = self.lstm(x,hidden)
        
        drop_output = self.dropout(lstm_output)
        
        drop_output = drop_output.contiguous().view(-1,self.num_hidden)
        
        final_out = self.fc_linear(drop_output)
        
        return final_out,hidden
    
    def hidden_state(self,batch_size):
        
        if self.use_gpu:
            
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda(),
                      torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda())
            
        else:
            
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden),
                      torch.zeros(self.num_layers,batch_size,self.num_hidden))
            
        return hidden

In [46]:
model = CharModel(all_chars=all_characters,
                 num_hidden=512,
                 num_layers=3,
                 drop_prob=0.5,
                 use_gpu=True)

In [47]:
total_param = []

for p in model.parameters():
    total_param.append(int(p.numel()))

In [48]:
# Rule of Thumb: Total parameter number is roughly equal to data length, means hidden layer number is good.
sum(total_param)

5470292

In [49]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
criterion = nn.CrossEntropyLoss()

In [55]:
train_percent = 0.9

In [56]:
# Training index
train_ind = int(len(encoded_text) * train_percent)

In [57]:
train_data = encoded_text[:train_ind]

In [58]:
val_data = encoded_text[train_ind:]

In [59]:
# Variables

In [60]:
epochs = 60
batch_size = 100

seq_len = 100

tracker = 0

num_char = max(encoded_text)+1

In [63]:
model.train()

if model.use_gpu:
    model.cuda()
    
for i in range(epochs):
    
    hidden = model.hidden_state(batch_size)
    
    for x,y in generate_batches(train_data,batch_size,seq_len):
        
        tracker += 1
        
        x = one_hot_encoder(x, num_char)
        
        inputs = torch.from_numpy(x)
        targets = torch.from_numpy(y)
        
        if model.use_gpu:
            
            inputs = inputs.cuda()
            targets = targets.cuda()
            
        hidden = tuple([state.data for state in hidden])
        
        model.zero_grad()
        
        lstm_output,hidden = model.forward(inputs,hidden)
        loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
        loss.backward()
        
        nn.utils.clip_grad_norm_(model.parameters(),max_norm=5)
        
        optimizer.step()
        
        if tracker % 25 == 0:
            
            val_hidden = model.hidden_state(batch_size)
            val_losses = []
            model.eval()
            
            for x,y in generate_batches(val_data,batch_size,seq_len):
                
                x = one_hot_encoder(x, num_char)
        
                inputs = torch.from_numpy(x)
                targets = torch.from_numpy(y)
                
                if model.use_gpu:
                    
                    inputs = inputs.cuda()
                    targets = targets.cuda()
                    
                val_hidden = tuple([state.data for state in val_hidden])
                
                lstm_output,val_hidden = model.forward(inputs,val_hidden)
                val_loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
                
                val_losses.append(val_loss.item())
                
            model.train()
            
            print(f"EPOCH: {i} Step: {tracker} VAL LOSS: {val_loss.item()}")

AssertionError: Torch not compiled with CUDA enabled